version: '3.1'


services:
   elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
       container_name: es01
       environment:
         - 'discovery.type=single-node'
       ports:
         - '9200:9200'
         - '9300:9300'